# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
# This vagrantfile creates a VM that is capable of building and testing
# the fabric core.

Vagrant.require_version ">= 1.7.4"
Vagrant.configure('2') do |config|
  config.vm.box = "bento/ubuntu-18.04"
  # config.vm.box = "geerlingguy/ubuntu1804"
  config.vm.synced_folder "..", "/home/vagrant/insurance-app"
  config.ssh.forward_agent = true

  config.vm.network :forwarded_port, guest: 3000, host: 3000, id: "web", host_ip: "localhost", auto_correct: true # insurance-app
  # config.vm.network :forwarded_port, guest: 7050, host: 7050, id: "orderer", host_ip: "localhost", auto_correct: true # fabric orderer service

  # config.vm.network :forwarded_port, guest: 7051, host: 7051, id: "insurance_peer", host_ip: "localhost", auto_correct: true # fabric peer service
  # config.vm.network :forwarded_port, guest: 7053, host: 7053, id: "insurance_peer_event", host_ip: "localhost", auto_correct: true # fabric peer event service
  # config.vm.network :forwarded_port, guest: 7054, host: 7054, id: "insurance_ca", host_ip: "localhost", auto_correct: true # fabric-ca service

  # config.vm.network :forwarded_port, guest: 8051, host: 8051, id: "shop_peer", host_ip: "localhost", auto_correct: true # fabric peer service
  # config.vm.network :forwarded_port, guest: 8053, host: 8053, id: "shop_peer_event", host_ip: "localhost", auto_correct: true # fabric peer event service
  # config.vm.network :forwarded_port, guest: 8054, host: 8054, id: "shop_ca", host_ip: "localhost", auto_correct: true # fabric-ca service

  # config.vm.network :forwarded_port, guest: 9051, host: 9051, id: "repairshop_peer", host_ip: "localhost", auto_correct: true # fabric peer service
  # config.vm.network :forwarded_port, guest: 9053, host: 9053, id: "repairshop_peer_event", host_ip: "localhost", auto_correct: true # fabric peer event service
  # config.vm.network :forwarded_port, guest: 9054, host: 9054, id: "repairshop_ca", host_ip: "localhost", auto_correct: true # fabric-ca service

  # config.vm.network :forwarded_port, guest: 10051, host: 10051, id: "police_peer", host_ip: "localhost", auto_correct: true # fabric peer service
  # config.vm.network :forwarded_port, guest: 10053, host: 10053, id: "police_peer_event", host_ip: "localhost", auto_correct: true # fabric peer event service
  # config.vm.network :forwarded_port, guest: 10054, host: 10054, id: "police_ca", host_ip: "localhost", auto_correct: true # fabric-ca service

  config.vm.provider :virtualbox do |vb|
    vb.name = "insurance-app"
    vb.cpus = 2
    vb.memory = 4096
  end

  # config.vm.provision :shell, name: "essentials", path: "essentials.sh"
  config.vm.provision :shell, name: "docker", path: "docker.sh"
  # config.vm.provision :shell, name: "golang", path: "golang.sh"
  # config.vm.provision :shell, name: "limits", path: "limits.sh"
  # config.vm.provision :shell, name: "softhsm", path: "softhsm.sh"
  # config.vm.provision :shell, name: "user", privileged: false, path: "user.sh"
end

# -*- mode: ruby -*-
# vi: set ft=ruby :
